displayName=Trade Tracker
author=botanicvelious
support=https://github.com/botanicvelious/runelite-trade-tracker
description=Records a detailed, searchable history of past trades with other players
tags=trade,history,track,item,log,logger,memory,lend
plugins=org.asundr.TradeTrackerPlugin
build=standard
